### ISSUE TITLE
Unable to Move

### ISSUE THREAD

**Issue by aldahl** [Raicuparta/two-forks-vr#230]
I'm unable to move in the game using the stick. The stick works fine using the teleport locomotion, but without enabling that, Henry is stuck. All other controls seem to work fine, and changing the settings for controller-based movement and swapping the left and right hands doesn't resolve the issue. I'm not sure if I'm missing something or if this is an issue specific to my setup. Other than this, the mod works great and I'm enjoying it very much!

I'm using an HP Reverb G2 with the included controllers and I'm running the game through Steam.

**Comment by Raicuparta** [comment]
So you're stuck right at the elevator at the beginning? Or did you get stuck some time after?
Try going to the SteamVR input bindings settings and check if the bindings for smooth movement look correct. The reverb G2 is supposed to use the same bindings as Oculus, and those seem to be working fine, so this is a bit strange.

**Comment by aldahl** [comment]
This happens anywhere, whether it's in the elevator in a new game or wherever I left off in a save. But like I said, pressing the stick forward to teleport fixed camera mode works fine.
Testing the controllers shows that all inputs are working, and I tried it in your Outer Wilds mod (which, may I add, is excellent) and it works there, so it's not a hardware issue.
As far as I can tell, the bindings all look correct. I've tried modifying them as well as changing the controller type, but to no effect. I've attached a picture of my movementhand bindings, but they look fine to me. Let me know if there's anything else I can provide that may be helpful.
![bindings](https://user-images.githubusercontent.com/8559344/171542225-8c815616-541b-4957-97d2-817ef2859c8d.jpg)

**Comment by Raicuparta** [comment]
Is smooth rotation working correctly for you?

**Comment by aldahl** [comment]
Yep, that works fine.

**Comment by aldahl** [comment]
A clean install of Windows resolved this.
