### ISSUE TITLE
Compilation Issues In VS Solution

### ISSUE THREAD

**Issue by MCrawley1** [Raicuparta/two-forks-vr#232]
Apologies if I'm missing something here, I've never developed mods before although I am very experienced in .Net and VR development so thought I'd try to get involved in this and maybe future mods.

I've cloned the repo but I'm seeing the solution (TwoForksVr.sln) doesn't compile - I'm seeing a lot of errors, so I was hoping to query them as they might be expected.

Incorrectly defined namespaces, eg "namespace TwoForksVr.Settings;"
Shouldn't the namespaces surround the class? I'm getting compilation issues right now because they don't.
Update: This is a C#10 thing! I'm clearly behind the times.

Unresolved Dependencies
It seems my VS is also unable to resolve the SteamVR dependency. Looking at the prebuild steps, it looks like they're copied from the UnityHelper - Is there any info anywhere how the UnityHelper should be built? It looks like it should be opened in Unity but that's as much as I can work out.

The BepInEx.Core also seems to be unresolved as well, and I'm unable to locate the right package on Nuget. Is there anything in particular we need to be doing to resolve this dependency?

If there's a developer guide anywhere or if there's a better place to ask these questions please let me know.

**Comment by MCrawley1** [comment]
Turned out to be an issue with me using an older version of VS. Updated to 2022 and now everything compiles fine.

**Comment by Raicuparta** [comment]
Sorry that I haven't added build instructions yet! I'll make sure to add them asap. Glad you managed to get it working.

What version of VS were you trying to use? I would expect this project to work with VS 2019 too, don't wee why it wouldn't. And I guess I need to make sure it specifies the C# version explicitly to avoid problems like these.

The problem with missing DLLs like steamvr os because you need to build the project once for the DLLs to get generated. So I guess you ended up doing that accidentally? Sorry about the confusion.

By the way, may I ask what kind of contribution you want to make? You can talk to me on Discord about it if you want to.

**Comment by MCrawley1** [comment]
> Sorry that I haven't added build instructions yet! I'll make sure to add them asap. Glad you managed to get it working.
> 
> What version of VS were you trying to use? I would expect this project to work with VS 2019 too, don't wee why it wouldn't. And I guess I need to make sure it specifies the C# version explicitly to avoid problems like these.
> 
> The problem with missing DLLs like steamvr os because you need to build the project once for the DLLs to get generated. So I guess you ended up doing that accidentally? Sorry about the confusion.
> 
> By the way, may I ask what kind of contribution you want to make? You can talk to me on Discord about it if you want to.

No worries, I guess this is in LTS now anyway so more changes are unlikely. 

I was using VS2019 which doesn't support C#10, but it also obviously had an impact on other things too like the resolving of dependencies. Once I upgraded then everything fell into place.

In regards to what I'm planning, more familiarising myself initially then I hope to re-engineer this into other games starting with Among Trees.

Will reach out on Discord shortly as I suspect I'll have a number of questions.

**Comment by Raicuparta** [comment]
You can join the Flat 2 VR Discord and find me there with the same name: https://discord.gg/gEEqTVFzvD
Plus you'll have other people helping you with this.

I didn't realize VS2019 didn't support C#10. I might try to change that just to make it easier to contribute to. Anyway, I added some proper build instructions for anyone else who might need them, thanks!
