### ISSUE TITLE
World doesn't load from save game

### ISSUE THREAD

**Issue by StoofManley** [Raicuparta/two-forks-vr#238]
I played this mod for the first time the other day and really enjoyed it. After loading my game again today (Day 2 in the game), The character loads but there is just an empty blue environment. None of the world map loads.

**Comment by Raicuparta** [comment]
I'm guessing the save is corrupted for some reason. Never saw that happen myself, but I've seen reports of something similar happening in the flat version too. I think your only solution might be to open the pause menu and restart the day.
